a="VR MALL"
y=0
q=0
v=0
print(a.center(80,"*"))
for i in range(100):
   print("1.Admin , 2.user 3.EXIT")
   z=int(input("select any one"))
   if z==2:
            for i in  range(100):
                          print("1.3 ,2.JOE 3.Hi Nanna")
                          c=int(input("select any one"))
                          if c==1:
                             if q==0:
                                 for i in range(1,100,10):
                                          for j in range(i,i+10):
                                               print(j,end=" ")
                                          print()                                    
                                 print("no of seats=5")
                                 d=int(input("select seat number"))
                                 k=int(input("select  seat number"))
                                 l=int(input("select  seat number"))
                                 m=int(input("select  seat number"))
                                 n=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d  or j==k or j==l or j==m or j==n:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 q=q+1
                             elif q==1:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d  or j==k or j==l or j==m or j==n:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()
                                 print("no of seats=5")
                                 d1=int(input("select seat number"))
                                 k1=int(input("select  seat number"))
                                 l1=int(input("select  seat number"))
                                 m1=int(input("select  seat number"))
                                 n1=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d1 , k1 ,l1 ,m1  ,n1 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d  or j==k or j==l or j==m or j==n or j==d1 or j==k1 or j==m1 or j==n1 or j==l1:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 q=q+1             
                             elif q==2:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d  or j==k or j==l or j==m or j==n or j==d1 or j==k1 or j==m1 or j==n1 or j==l1:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("no of seats=5")
                                 d2=int(input("select seat number"))
                                 k2=int(input("select  seat number"))
                                 l2=int(input("select  seat number"))
                                 m2=int(input("select  seat number"))
                                 n2=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d2 , k2 ,l2 ,m2  ,n2 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d  or j==k or j==l or j==m or j==n or j==d1 or j==k1 or j==m1 or j==n1 or j==l1 or j==d2 or j==k2 or j==l2 or j==m2 or j==n2 :   
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()                                             
                                 print("Thanks for purchasing")

                          if  c==2 :
                             if v==0:
                                 for i in range(1,100,10):
                                          for j in range(i,i+10):
                                               print(j,end=" ")
                                          print()                                    
                                 print("no of seats=5")
                                 d11=int(input("select seat number"))
                                 k11=int(input("select  seat number"))
                                 l11=int(input("select  seat number"))
                                 m11=int(input("select  seat number"))
                                 n11=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d11  or j==k11 or j==l11 or j==m11 or j==n11:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 v=v+1
                             elif v==1:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d11  or j==k11 or j==l11 or j==m11 or j==n11:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("no of seats=5")
                                 d12=int(input("select seat number"))
                                 k12=int(input("select  seat number"))
                                 l12=int(input("select  seat number"))
                                 m12=int(input("select  seat number"))
                                 n12=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d12 , k12 ,l12 ,m12  ,n12 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d11  or j==k11 or j==l11 or j==m11 or j==n11 or j==d12 or j==k12 or j==m12 or j==n12 or j==l12:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 v=v+1             
                             elif v==2:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d11  or j==k11 or j==l11 or j==m11 or j==n11 or j==d12 or j==k12 or j==m12 or j==n12 or j==l12:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()
                                 print("no of seats=5")
                                 d22=int(input("select seat number"))
                                 k22=int(input("select  seat number"))
                                 l22=int(input("select  seat number"))
                                 m22=int(input("select  seat number"))
                                 n22=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d22 , k22 ,l22 ,m22  ,n22 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d11  or j==k11 or j==l11 or j==m11 or j==n11 or j==d12 or j==k12 or j==m12 or j==n12 or j==l12 or j==d22 or j==k22 or j==l22 or j==m22 or j==n22 :   
                                                     print("X", end=" ")
                                                 else:
                                                    print(j ,end=" ")
                                              print()                                              
                                 print("Thanks for purchasing")

                          if c==3 :
                            if y==0:
                                 for i in range(1,100,10):
                                          for j in range(i,i+10):
                                               print(j,end=" ")
                                          print()                                    
                                 print("no of seats=5")
                                 d31=int(input("select seat number"))
                                 k31=int(input("select  seat number"))
                                 l31=int(input("select  seat number"))
                                 m31=int(input("select  seat number"))
                                 n31=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d31  or j==k31 or j==l31 or j==m31 or j==n31:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 y=y+1
                            elif y==1:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d31  or j==k31 or j==l31 or j==m31 or j==n31:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()
                                 print("no of seats=5")
                                 d41=int(input("select seat number"))
                                 k41=int(input("select  seat number"))
                                 l41=int(input("select  seat number"))
                                 m41=int(input("select  seat number"))
                                 n41=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d41 , k41 ,l41 ,m41  ,n41 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d31  or j==k31 or j==l31 or j==m31 or j==n31 or j==d41 or j==k41 or j==m41 or j==n41 or j==l41:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()

                                 print("Thanks for purchasing")
                                 y=y+1             
                            elif y==2:
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d31  or j==k31 or j==l31 or j==m31 or j==n31 or j==d41 or j==k41 or j==m41 or j==n41 or j==l41:
                                                     print("X", end=" ")

                                                 else:
                                                    print(j ,end=" ")
                                              print()
                                 print("no of seats=5")
                                 d51=int(input("select seat number"))
                                 k51=int(input("select  seat number"))
                                 l51=int(input("select  seat number"))
                                 m51=int(input("select  seat number"))
                                 n51=int(input("select  seat number"))
                                 print(" you ticket has been  booked sucessfully")
                                 print("your booking ticket is " , d51 , k51 ,l51 ,m51  ,n51 )
                                 print("Availble tickets")
                                 for i in range(1,100,10):
                                              for j in range(i,i+10):
                                                 if j==d31  or j==k31 or j==l31 or j==m31 or j==n31 or j==d41 or j==k41 or j==m41 or j==n41 or j==l41 or j==d51 or j==k51 or j==l51 or j==m51 or j==n51 :   
                                                     print("X", end=" ")
                                                 else:
                                                    print(j ,end=" ")
                                              print()                                              
                                 print("Thanks for purchasing")

                          else:
                             print("give the correct data")
                             continue
                          print("1.Book again 2.Exit")
                          e=int(input("Select any one"))                          
                          if e==2:                             
                             break             
   if z==1:
       for i in range(100):
           print("1.New movie, 2.modify , 3.Exit")
           b=int(input("select any one"))
           if b==1:
               nm1=input("enter the movie name")
               nm2=input("enter the shows")
               nm3=input("enter the timings")               
               print("1. Movie name: " ,nm1 ," NO OF SHOWS:",nm2,"Timings-",nm3 )
               print("New movie added")
           elif b==2:
                print("1. Movie name: 3 ' NO OF SHOWS:5 , Timings- 5:00,7:00,10:00,1:00,7:00,10:00")
                print("2. Movie name: JOE ' NO OF SHOWS:3 , Timings- 1:00 , 6:00, 9:00")
                print("3. Movie name: Hi Nanna ' NO OF SHOWS:4, Timings - 10:00,4:00,8:00,11:00")
                m1=int(input("select modify movie name"))           
                if m1==1:
                   mt1=int(input("enter the available shows"))
                   mt2=(input("enter the available times "))
                   print("1. Movie name: 3 ' NO OF SHOWS:" , mt1 ," , Timings-"  ,mt2)      
                   print(" MOVIE SHOWS & TIME   MODIFIED")              
                if m1==2:
                   mt3=int(input("enter the available shows"))
                   mt4=(input("enter the available times "))
                   print("1. Movie name: 3 ' NO OF SHOWS:" ,mt3, " , Timings-" , mt4)      
                   print(" MOVIE SHOW & TIME   MODIFIED")                   
                if m1==3:
                   mt5=int(input("enter the available shows"))
                   mt6=(input("enter the available times "))
                   print("1. Movie name: 3 ' NO OF SHOWS:" , mt5 ," , Timings-" , mt6)      
                   print(" MOVIE SHOW & TIME   MODIFIED")
           elif b==3:
                    break           

   if z==3:
       print("select correct option")
       print("program ended")
       break
           
         
         
